### ISSUE TITLE
add ability adjust padding on decimal

### ISSUE THREAD

**Issue by JefferyEmanuel** [fabiomsr/MoneyTextView#6]
I'd like to adjust the height of the superscript. right now the gravity is just top or bottom . could you make one for center or the ability to add padding so i can push the decimal text down to my specification ?  Or can you show me how you got it like this screenshot: 
<img width="265" alt="screen shot 2017-04-03 at 11 54 20 pm" src="https://cloud.githubusercontent.com/assets/24399680/24644514/d5d84c90-18c8-11e7-91cf-8e1186625d36.png">

because i see thats what i want but your examples dont demo how the decimal part can be perfectly aligned with the dollar part like in that photo.

**Comment by fabiomsr** [comment]
Hi,

You only need to set both symbolGravity and decimalGravity:

```xml
        app:symbolGravity="start|top"
        app:decimalGravity="top"
```

Try this:

  ```xml
<org.fabiomsr.moneytextview.MoneyTextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:symbol="$"
        app:amount="99.99"

        app:symbolGravity="start|top"
        app:decimalGravity="top"

        app:symbolTextSize="18sp"
        app:baseTextSize="35sp"
        app:decimalDigitsTextSize="18sp"

        app:decimalMargin="6dp"
        app:symbolMargin="6dp"
        app:includeDecimalSeparator="false"
        app:baseTextColor="#FBFFE3"/>
```

![example](https://cloud.githubusercontent.com/assets/5305689/24675182/83869dd2-197e-11e7-9e85-e8f5d2908625.jpg)

**Comment by JefferyEmanuel** [comment]
your comments showed me how to do this. the android preview window wasn't updating for some reason but at runtime everything renders fine. excellent.
